.\" Manpage for http-notify.
.\" Contact trimstray@gmail.com.
.TH man 8 "16.10.2018" "v1.0.0" "http-notify man page"
.SH NAME
http-notify \- keep track of all http activities
.SH SYNOPSIS
http-notify <option|long-option>
.SH DESCRIPTION
http-notify - keep track of all http activities
.SH OPTIONS
-h|--help
        show this message
-t|--type
        http server type: nginx or apache
-m|--mode
        mode type: stats or monitor
-l|--logfile
        path to logfile
-f|--filter
        set filter (e.g. by url)
.SH SEE ALSO
https://github.com/trimstray/http-notify
.SH BUGS
No known bugs.
.SH AUTHOR
Michał Żurawski (trimstray@gmail.com)
